#if !canImport(ObjectiveC)
import XCTest

extension CommandShellTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandShellTests = [
        ("testBasics", testBasics),
        ("testHelp", testHelp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandShellTests.__allTests__CommandShellTests),
    ]
}
#endif
