#if !canImport(ObjectiveC)
import XCTest

extension CommandShellTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandShellTests = [
        ("testHelp", testHelp),
        ("testNoCommands", testNoCommands),
        ("testSubcommand", testSubcommand),
        ("testSubcommandVerbose", testSubcommandVerbose),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandShellTests.__allTests__CommandShellTests),
    ]
}
#endif
